name: to_do_list
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  slideable: ^0.0.2
  google_fonts: ^6.3.2
  percent_indicator: ^4.2.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  awesome_dialog: ^3.3.0
  fl_chart: ^1.1.1
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# إعدادات أيقونة التطبيق - يجب أن تكون مستقلة في هذا المستوى
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # تأكد من أن المسافات هنا دقيقة (فراغان قبل assets وأربعة قبل الشرطة)
  assets:
    - assets/icon/icon.png